sudo: required
language: node
node_js:
  - latest
script: bash ./compile.sh
deploy:
  provider: pages
  local_dir: public
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
